export const useShowWidgets = () => useState('showWidgets', () => false)
export const useShowPopup = () => useState('showPopup', () => false)
export const useShowVideoModal = () => useState('showVideoModal', () => false)
export const useShowMobMenu = () => useState('showMobMenu', () => false)
export const useShowShare = () => useState('showShare', () => false)
export const useLangSwitcher = () => useState('langSwitcher', () => false)